/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package rs.fon.np.application.kkfunakoshi.view.form;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import rs.fon.np.application.kkfunakoshi.controller.ControllerUI;
import rs.fon.np.application.kkfunakoshi.domain.Category;
import rs.fon.np.application.kkfunakoshi.domain.Medal;
import rs.fon.np.application.kkfunakoshi.domain.Result;

/**
 * Forma koja prikazuje podatke o konkretnom rezultatu tima karate kluba.
 * @author Jelena Repac
 */
public class FrmLoadResultTeam extends javax.swing.JDialog {

	/**
	* Rezultat koji se prikazuje na formi
    */
    Result r=null;
    /**
     * Konstruktor, kreira novi prozor FrmLoadResult
     * @param parent forma iz koje je pozvana 
     * @param modal odredjuje da li dijalog treba da bude modalan ili ne 
     * @param r rezultat koji se prikazuje na formi
     */
    public FrmLoadResultTeam(java.awt.Frame parent, boolean modal,Result r) {
        super(parent, modal);
        this.r=r;
        initComponents();
        
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        try { 
            
            JOptionPane.showMessageDialog(parent, "System load result.");
            prepareView();
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(parent, "System can't load result", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCompetition = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbMedals = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbCategory = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTeam = new javax.swing.JTextField();
        btnResultTeam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Competition:");

        jLabel3.setText("Medal:");

        cbMedals.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Category");

        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Team:");

        btnResultTeam.setText("Update team result");
        btnResultTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultTeamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMedals, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnResultTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCompetition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbMedals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnResultTeam)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Obradjuje dogadjaj kada se pritisne dugme ResultTeam.
     * Omogucava promenu informacija vezanih za ostvareni rezultat tima.
     * Vrsi azuriranje rezultat u bazi.
     * @param evt dogadjaj koji pokrece ovu metodu
     */
    private void btnResultTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultTeamActionPerformed
        try {
            Result newResult= new Result();
            newResult.setMedals((Medal) cbMedals.getSelectedItem());
            newResult.setCategory((Category) cbCategory.getSelectedItem());
            newResult.setCompetition(r.getCompetition());
            newResult.setMember(r.getMember());
            newResult.setTeam(r.getTeam());
            
           
            ControllerUI.getInstance().updateResult(r,newResult);
            
            
            JOptionPane.showMessageDialog(this, "Succesfully updated result!");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnResultTeamActionPerformed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultTeam;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JComboBox<String> cbMedals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCompetition;
    private javax.swing.JTextField txtTeam;
    // End of variables declaration//GEN-END:variables
    /**
     * Priprema prikaz forme.
     */
    private void prepareView() {
        load();
        setValues();
       
    }
    /**
     * Postavlja pocetne vrednosti polja forme.
     */
    private void load() {
        cbCategory.setModel(new DefaultComboBoxModel(Category.values()));
        cbMedals.setModel(new DefaultComboBoxModel(Medal.values()));
        
    }
    /**
     * Postavlja vrednosti atributa prosledjenog rezultata.
     */
    private void setValues() {
       txtCompetition.setText(r.getCompetition().toString());
       txtTeam.setText(r.getTeam().toString());
       txtTeam.setEditable(false);
       txtCompetition.setEditable(false);
       cbCategory.setSelectedItem(r.getCategory());
       cbMedals.setSelectedItem(r.getMedals());
    }
}
