/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.fon.np.application.kkfunakoshi.view.form;

import java.io.IOException;
import java.net.Socket;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import rs.fon.np.application.kkfunakoshi.controller.ControllerUI;
import rs.fon.np.application.kkfunakoshi.domain.CurrentUser;
import rs.fon.np.application.kkfunakoshi.domain.Trainer;
import rs.fon.np.application.kkfunakoshi.validation.ValidationException;


/**
 * Predstavlja formu za prijavljivanje korisnika na sistem.
 * @author Jelena Repac
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Trener, korisnik koji se prijavljuje na sistem.
     */
   private Trainer currentUser;
   /**
    * Glavna forma
    */
   private FrmMain frmMain;
   
   /**
    * Vraca glavnu formu
    * @return frmMain
    */
    public FrmMain getFrmMain() {
        return frmMain;
    }
    /**
     * Konstruktor, kreira novu formu FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setTitle("Login");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtPassword.setText("daca2000");
        txtUser.setText("daca");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUser.setText("Username");

        lblPassword.setText("Password");

        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(lblPassword))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUser)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword)))
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Obradjuje dogadjaj kada se pritisne dugme Login.
     * Vrsi validaciju unetih podataka i prijavljuje korisnika na sistem.
     * Prikazuje prozor sa porukom ukoliko dodje do greske prilikom unosa podataka ili greske prijavljivanja na sistem.
     * @param evt dogadjaj koji pokrece ovu metodu
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
       
        try {
            String username= getTxtUser().getText().trim();
            String password= String.copyValueOf(getTxtPassword().getPassword());
            validateForm(username,password);
            
            currentUser=ControllerUI.getInstance().login(username, password);
            CurrentUser.setCurrentUser(currentUser);
            JOptionPane.showMessageDialog(this, "Welcome, " + currentUser.getFirstname()+" "+currentUser.getLastname());
            this.dispose();
            frmMain=new FrmMain(currentUser,new Socket());
            frmMain.setVisible(true);
         } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + "Server is stopped working.", "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            
        }
       
    }//GEN-LAST:event_btnLoginActionPerformed

    
	/**
	 * Postavlja vrednost lozinke
	 * @param txtPassword lozinka korisnika
	 */
    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }
    /**
     * Vraca JTextField komponentu
     * @return JTextField 
     */
    public JTextField getTxtUser() {
        return txtUser;
    }

    /**
     * Postavlja vrednost korisnickog imena
     * @param txtUser korisnicko ime
     */
    public void setTxtUser(JTextField txtUser) {
        this.txtUser = txtUser;
    }
    /**
     * Vraca komponentu JPasswordField
     * @return JPasswordField komponenta
     */
    public javax.swing.JPasswordField getTxtPassword() {
		return txtPassword;
	}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    /**
     * Vrsi validaciju korisnickog unosa za korisnicko ime i lozinku.
     * Koristi Validator klasu za proveru i generisanje odgovarajuce poruke o gresci.
     * 
     * @throws ValidationException Ukoliko postoji neka greška u unosu
     */
    private void validateForm(String username, String password) throws Exception {
        String errorMessage="";
        if(username.isEmpty()){
            errorMessage+="Username can not be empty!\n";
        }
        if(password.isEmpty()){
            errorMessage+="Password can not be empty!\n";
        }
        if(!errorMessage.isEmpty()){
            throw new Exception("You must fill username and password");
        }
    }
}
